# Application configuration
spring.application.name=SpringSecurityDemo
server.port=8081

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging Spring Security
logging.level.org.springframework.security=DEBUG